// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Simple is an autogenerated mock type for the Simple type
type Simple struct {
	mock.Mock
}

// GetAbc provides a mock function with given fields:
func (_m *Simple) GetAbc() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAbc provides a.0 mock function with given fields: _a0, _a1
func (_m *Simple) SetAbc(_a0 string, _a1 int) {
	_m.Called(_a0, _a1)
}
